name: C++ Build
on: [push]
jobs:
  cmake-build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1        
      - name: macos build and test
        if: matrix.os == 'macOS-latest'
        env:
          CC: clang
          CXX: clang++
        run: |
          mkdir ./build
          cd build
          cmake ..
          cmake --build .
        shell: bash
      - name: linux build and test
        if: matrix.os == 'ubuntu-latest'
        env:
          CC: gcc
          CXX: g++
        run: |
          pwd
          mkdir ./build
          cd build
          cmake ..
          cmake --build .
        shell: bash
