name: C++ Build
on: [push]
jobs:
  cmake-build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.12.6     
      - name: macos build and test
        if: matrix.os == 'macOS-latest'
        env:
          CC: clang
          CXX: clang++
        run: |
          brew install boost libtiff glm
          mkdir ./build
          cd build
          cmake ..
          cmake --build . --target agave_test --config Release
          sudo cmake --build . --target install --config Release
        shell: bash
      - name: linux build and test
        if: matrix.os == 'ubuntu-latest'
        env:
          CC: gcc
          CXX: g++
        run: |
          sudo apt-get install libboost-all-dev libtiff-dev libglm-dev libgl1-mesa-dev
          pwd          
          mkdir ./build
          cd build
          cmake ..
          cmake --build . --target agave_test --config Release
          cmake --build . --target install --config Release
        shell: bash
      - name: windows build and test
        if: matrix.os == 'windows-latest'
        run: |
          vcpkg install --triplet x64-windows tiff glm
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -A x64 ..
          cmake --build . --target agave_test --config Release
          cmake --build . --target install --config Release
        shell: cmd
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: Release.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
