name: C++ Release Build
on:
  push:
    tags:
      - v*

jobs:
  cmake-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Install Python 3.9 version
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
      - name: macos install deps
        if: matrix.os == 'macOS-latest'
        env:
          CC: clang
          CXX: clang++
        run: |
          export MACOSX_DEPLOYMENT_TARGET=10.12
          brew install boost glm
      - name: macos build and test
        if: matrix.os == 'macOS-latest'
        env:
          CC: clang
          CXX: clang++
        run: |
          export MACOSX_DEPLOYMENT_TARGET=10.12
          mkdir ./build
          cd build
          cmake ..
          cmake --build . --target agave_test --config Release
          sudo cmake --build . --target install --config Release
          zip -vr agave-macos.zip agave.app/
        shell: bash
      - name: Upload mac artifact
        if: matrix.os == 'macOS-latest'
        uses: actions/upload-artifact@v1
        with:
          name: agave-macos
          path: ./build/agave-macos.zip
      - name: linux install deps
        if: matrix.os == 'ubuntu-latest'
        env:
          CC: gcc
          CXX: g++
        run: |
          sudo apt-get install libboost-all-dev libglm-dev libgl1-mesa-dev libegl1-mesa-dev
      - name: linux build and test
        if: matrix.os == 'ubuntu-latest'
        env:
          CC: gcc
          CXX: g++
        run: |
          pwd
          mkdir ./build
          cd build
          cmake ..
          cmake --build . --target agave_test --config Release
          cmake --build . --target install --config Release
        shell: bash
      - name: windows install deps
        if: matrix.os == 'windows-latest'
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          vcpkg install --triplet x64-windows glm zlib libjpeg-turbo liblzma
      - name: windows install boost
        if: matrix.os == 'windows-latest'
        uses: MarkusJx/install-boost@v1.0.1
        with:
          boost_version: 1.72.0
          toolset: msvc14.2
        id: install-boost-windows
      - name: windows build and test
        if: matrix.os == 'windows-latest'
        env:
          vc_arch: ${{ matrix.msvc_arch }}
          BOOST_ROOT: ${{ steps.install-boost-windows.outputs.BOOST_ROOT }}
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE="%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -A x64 ..
          cmake --build . --target agave_test --config Release
          cmake --build . --target install --config Release
          powershell Compress-Archive -Path .\agave-install -DestinationPath agave-win.zip
        shell: cmd
      - name: Upload windows artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v1
        with:
          name: agave-win
          path: ./build/agave-win.zip

  publish_pythonclient:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Install Python 3.9 version
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: Build Package
        run: |
          cd agave_pyclient
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: aicspypi
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: agave_pyclient/dist/
          verbose: true

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
          build-command: "make latexpdf"
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: docs/_build/html/
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationPDF
          path: docs/_build/latex/agave.pdf
      - name: Publish Docs
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_build/html/ # The folder the action should deploy.
          CLEAN: true
  make-release:
    runs-on: ubuntu-latest
    needs: cmake-build
    steps:
      # Since Github actions (currently) doesn't provide a slugged version of the git tag we have to
      # create it by ourselves. It is then made available to other steps in this job as a step.outputs
      # variable
      - name: Get the version (git tag)
        id: get_version
        run: |
          echo ${GITHUB_REF/refs\/tags\/v/}
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Get mac build artifact
        uses: actions/download-artifact@v1
        with:
          name: agave-macos
      - name: Get windows build artifact
        uses: actions/download-artifact@v1
        with:
          name: agave-win
      - name: Get PDF documentation build artifact
        uses: actions/download-artifact@v1
        with:
          name: DocumentationPDF
      - name: Version the artifacts
        run: |
          mv ${{ github.workspace }}/agave-macos/agave-macos.zip ${{ github.workspace }}/agave-macos/agave-${{ steps.get_version.outputs.VERSION }}-macos.zip
          mv ${{ github.workspace }}/agave-win/agave-win.zip ${{ github.workspace }}/agave-win/agave-${{ steps.get_version.outputs.VERSION }}-win.zip
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: true
          files: |
            ${{ github.workspace }}/agave-macos/agave-${{ steps.get_version.outputs.VERSION }}-macos.zip
            ${{ github.workspace }}/agave-win/agave-${{ steps.get_version.outputs.VERSION }}-win.zip
            ${{ github.workspace }}/DocumentationPDF/agave.pdf
